python Novelty.py --data Hepatitis --stop_epochs 5 --full_space True --k 1
python Novelty.py --data Annthyroid --stop_epochs 10 --full_space True --k 1
python Novelty.py --data Cardiotocography --stop_epochs 62 --full_space True --k 1
python Novelty.py --data Waveform --stop_epochs 10 --full_space True --k 1
python Novelty.py --data fault --stop_epochs 15 --full_space True --k 1
python Novelty.py --data letter --stop_epochs 300 --full_space True --k 1
python Novelty.py --data Ionosphere --stop_epochs 300 --full_space True --k 1
python Novelty.py --data WPBC --stop_epochs 50 --full_space True --k 1
python Novelty.py --data landsat --stop_epochs 60 --full_space True --k 1
python Novelty.py --data satellite --stop_epochs 5 --full_space True --k 1
python Novelty.py --data satimage-2 --stop_epochs 50 --full_space True --k 1
python Novelty.py --data SpamBase --stop_epochs 62 --full_space True --k 1
python Novelty.py --data optdigits --stop_epochs 10 --full_space True --k 1
python Novelty.py --data mnist_0 --stop_epochs 10 --full_space True --k 1
python Novelty.py --data musk --stop_epochs 100 --full_space True --k 1
python Novelty.py --data Arrhythmia --stop_epochs 50 --full_space True --k 1
python Novelty.py --data speech --stop_epochs 100 --full_space True --k 1
python Novelty.py --data CIFAR10_0 --stop_epochs 17 --full_space True --k 1
python Novelty.py --data FashionMNIST_0 --stop_epochs 100 --full_space True --k 1
python Novelty.py --data SVHN_0 --stop_epochs 23 --full_space True --k 1
python Novelty.py --data InternetAds --stop_epochs 130 --full_space True --k 1
python Novelty.py --data 20news_0 --stop_epochs 200 --full_space True --k 1
python Novelty.py --data MVTec-AD_bottle --stop_epochs 200 --full_space True --k 1